openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /game/{gameId}/player/{playerId}/solution:
    post:
      tags:
      - game-controller
      operationId: solvePlayGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      - name: playerId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerGame'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PlayerGame'
  /game/{id}:
    get:
      tags:
      - game-controller
      operationId: getGameById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Game'
  /game/{gameId}/player/{playerId}/solve:
    get:
      tags:
      - game-controller
      operationId: getPlayGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      - name: playerId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    PlayerGame:
      type: object
      properties:
        id:
          type: integer
          format: int64
        playerId:
          type: integer
          format: int64
        gameId:
          type: integer
          format: int64
        gameDetails:
          type: string
        solve:
          type: boolean
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        gameDetails:
          type: string
        gameSolution:
          type: string
        gameComplexity:
          type: string
